### ISSUE TITLE
Can not getUSB port

### ISSUE THREAD

**Issue by carl1990** [yanbin92/SerialPortLibrary#1]
I use this lib but not get USB port info

**Comment by yanbin92** [comment]
SerialPortFinder mSerialPortFinder= new SerialPortFinder();
      String[] entryValues = mSerialPortFinder.getAllDevicesPath();
      List<String> allDevices = new ArrayList<String>();
  先确认有哪些串口

**Comment by yanbin92** [comment]
这个我是在做一个门禁ic卡读卡器将ic卡信息 ，通过232串口传给android主板时用到的  不是usb线吧
